GET http://localhost:8000/get-profile
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdHVkZW50SUQiOiI2MmExZTk4YzdlMzhhZDQ2M2RjYTVmMmQiLCJlbWFpbCI6Im1mcmVrZS52aWN0b3JAZ21haWwuY29tIn0.Rt7Aw9K4FKdfvyWHk2relrol7yRr1_PWGvWuLJF82bM
Content-Type: application/json




# {
#     "ciphertext": "YXy4aLtRjlN2ltwgdGOr1eHZjiDT8b-Ww3bOJ6HU4rEUP5yoxEwLgll67dZhLUKAYSPTYqqmHxEHiD06Wml_F7hPmKhbmmkKjP48Ei8uo-fo0turfIcGw31P_o6ME_31ZmNQt4RiwVWXBKcpL8vSGm_mjOGU4zGqid9ET6BaBms=",
#     "decryptionKey": "-----BEGIN RSA PRIVATE KEY-----\nMIICYAIBAAKBgQCK1gFilD3cDbb88AJ5pmzrdhVl3hNmZXGLNmwvzna8MeMinBN7\ns5vX8r68zF9a5+/aNrznBb1Az72elJ2Hz0j0BOSIKHeL56PRmwQPin9xa4DEzrRK\ne2122/ZpmjB5MHsIrStPtFY1Yp+EJYlPd4ubhEdslQTYJysOLQK+3OXPWQIDAQAB\nAoGAdTEgCi5H6TBKfke6TyWEW11ZwpsqlQycQ36048XLxB/4Moa8i3aY3jgxePyq\noPmXJQN/gSL/FW5GCU45E18bHVUSwXY39LB++b7OVS859ysfdLj/iE+3RkYRTCU4\nWKG4qJdz/1tQF6M2Au2qN3bSHyTcqG4viIC6NTuFEDna64ECRQCN4VuzyW/GRVuY\nnLiHQ1uuqBpgqsHEWfuw6gI/RQt1GoK8abyWm52Ieq7AAsGyAXbCSqRdxIQAYK5S\n8Helc39ca6mijQI9APqByMX/+kDi6c2LyX1KT4hIDSUSW9WVb43C4A9vz01UiZW/\nsoIXbVmlH4gIXppODmRC3vLV33xxvKtS/QJEMT8z8WfOIGgarxJXCrxaqnk3Dq62\nq00AjBvtw8BXhcI59uRMzYoeWC0dUxCh4wOXEUGPY+y+VNM6LxfAr/EzGAVW0FEC\nPQCkHhMjZSjXCdKTT1maM+0XI904xGZV76k9/sY8VsxBpXjeGtEgWajSalPWE2Wn\nQiw7k3PtNCFOrlUlCSECRAyPjmAuLLGFHIyhMDGJ88isi70juSxLx7a1LEynvbe9\ngApZ7T0YpFOQqh0V7ErrWjl4VH41MjIJxNeBdApIe0WgMHjm\n-----END RSA PRIVATE KEY-----\n"
# }

# {
#     "file": "../original.png"
# }


# My Public Key
# "-----BEGIN RSA PUBLIC KEY-----\nMIGJAoGBAKVoUgczS4Q4MCUfR1VHoJec5xsEiIvcIkwqDPU6x6rfI+p3NuJG/6Es\nTF01kK8i48Of9ZLtLzsDtaqd8PjT+t5HmIkg5cdXvbMPDwvOLA7tDqXH4mGJwGiB\nObzXBTshGlF1KmeFNf9TaXjQLtVl6VF8BWAzje+Sj8H/5vyKUk2pAgMBAAE=\n-----END RSA PUBLIC KEY-----\n"

# Cyher Text
# "Aa8rF2PKCbnIBGbIvDGRFN-IrOhJ8Gqe3e2gPADkGRMiA0c7ke0T0N7D2wYL35If4_O9OE5EwWYp6H8glUyov7Emgw_-GLkiMU--CJ_vUalwkyjiVsDxoojh-h2D1uuPB1gpgzpmu77PZHbcaJ1eCan8K6zKEEE6WZkvKTG_QYo="


# {
#     "ciphertext": "cYRS8DIHjW5RM_7RexIOY-oGOq4KGvEyR4Ea9vY6a9IJKqp3uTOPlbK2_XK2cBWiCQK6fkvBDtKmnwXotsB25EfmulZxL1sQpIIy9MVAzC7LoLM9kYnCJ6vVat76GdAoGF-qbiyBlMlgWqHFxLczuwU4DZS3mGTM4Xgev16u3cE=",
#     "decryptionKey": "-----BEGIN RSA PRIVATE KEY-----\nMIICYAIBAAKBgQCTx3FL3bmpPYBzmDdp46Xl91BmrJheNYcOKh0QzdIxghTd5rRE\nhDvEQSBxrIbUGAxom9FsAxmMig7nN0aH4Gk3h2tZOAjXB4eQVbCBM1S0AtAgsBfq\njndW6LsQr/9IUfw9dKI7rVV+E5/+m3hJEgwDXeZUD5kEEh90aQpkHvDpswIDAQAB\nAoGAHhLTaqYHt3pNnriWZlUumLsYwJxVMa7g+i/11EqegPbA+luNyffDFfBPAvMi\nSR1PwSYcm0eSNniOCd3Et4bohMXs1ZzGnz18pW2l7P4agHROdRgOgDqngMeamEyD\nbsP53TIwl9yv1x4gbTYTIgQUx6dQM1AdkTubqlEv7T/PO5ECRQCx1+0SUjMspylx\nsZDF39iCkWyjDRCtwU+FsWLWZMJbPm4jC1i1kRfBy2u1o8gbmk7raxdRpHSXPvIF\nYoQjB7q7PjTjqQI9ANS5KDS73d9QkvuTmlgioaC2iL5d8ZrFi8D0TWcGl5dpj8P5\nHYahBczTisNA9CAXI6v6ky5okfcRUkf7+wJFAI0SLRoFXlajWvq20ZJE2CfqV3SX\nXo2V9BCm/zH1xz49rXva+kk8iM3PIOd6vbc3ljakQmEexOVcpvqihRKMhREWbTnR\nAjxTP+MsQBmku7PKIQnWVDdM3iLF3Z4gJA99hB6Go13QM8+/sk6L0ZijgGZd452m\nsWeUdowDLYlyV6UL5uECRFFnq6PwoUnK3ns704pkGwkCLYdpuVct8mocUBcNzTWx\n/9/2Eto/gvmhrotZhoSWakgUfDo4utscX4VNdFembWm/fOrh\n-----END RSA PRIVATE KEY-----\n"
# }

# {
#     "keyLength": "1024",
#     "PKReceiversEmail": "victorp3tr@gmail.com"
# }

# {
#     "text": "Hello Everyone",
#     "encryptionKey": "-----BEGIN RSA PUBLIC KEY-----\nMIGJAoGBAJPHcUvduak9gHOYN2njpeX3UGasmF41hw4qHRDN0jGCFN3mtESEO8RB\nIHGshtQYDGib0WwDGYyKDuc3RofgaTeHa1k4CNcHh5BVsIEzVLQC0CCwF+qOd1bo\nuxCv/0hR/D10ojutVX4Tn/6beEkSDANd5lQPmQQSH3RpCmQe8OmzAgMBAAE=\n-----END RSA PUBLIC KEY-----\n"
# }

{
    "email": "mfreke.victor@gmail.com",
    "password": "5678"
}
